### ISSUE TITLE
Generated passwords are being repeated, look into that

### ISSUE THREAD

**Issue by unamdev0** [diveshlunker/Brute-Force-Passwords#1]
![Screenshot (254)](https://user-images.githubusercontent.com/35065474/59489705-93608a80-8ea0-11e9-9f96-8904d626c3b8.png)

**Comment by diveshlunker** [comment]
Issue been resolved. Thank you for bringing it to notice.
Have a good day:)

![Screenshot (530)](https://user-images.githubusercontent.com/29224349/59835543-7677fb80-9367-11e9-9e4a-c690d8a06531.png)
