### ISSUE TITLE
Possibility of more passwords; Look into that

### ISSUE THREAD

**Issue by unamdev0** [diveshlunker/Brute-Force-Passwords#2]
@diveshlunker 

There can be more passwords generated for eg. in the following case there can be a password 'Acm', but as I increase the count it shows that it is not possible
![Screenshot (265)](https://user-images.githubusercontent.com/35065474/59839976-2a30b980-936f-11e9-9b2e-d2e11a1a3a0b.png)
![Screenshot (266)](https://user-images.githubusercontent.com/35065474/59839978-2ac95000-936f-11e9-9965-e38f47bc18bf.png)
![Screenshot (267)](https://user-images.githubusercontent.com/35065474/59839980-2ac95000-936f-11e9-8fae-2b1aac4eabb8.png)

**Comment by diveshlunker** [comment]
Issue resolved.
